 name: Data Theorem SAST

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: us-central1-docker.pkg.dev/prod-scandal-us/datatheorem-sast/datatheorem-sast:latest
      env:
        DT_SAST_API_KEY: ${{ secrets.DT_RESULTS_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Start Data Theorem SAST Scan
        run: python /app/main.py scan --name="jc-demo-env/Android-InsecureBankv2" --repo-platform=GITHUB --repo-id="733553980" --repo-html-url="https://github.com/jc-demo-env/Android-InsecureBankv2.git" --repo-default-branch-name=${{ github.event.repository.default_branch }}  --output-dir=$PWD
      # Optional step to make scan results available as a Github artifact
      - uses: actions/upload-artifact@v4
        with:
          name: dt-sast-scan-result
          path: ./scan-results-sarif.json
